// Mocks generated by Mockito 5.4.6 from annotations
// in orbit_task/test/orbit_task_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:orbit_task_platform_interface/orbit_task_platform_interface.dart'
    as _i3;
import 'package:orbit_task_platform_interface/src/task.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskConstraints_0 extends _i1.SmartFake
    implements _i2.TaskConstraints {
  _FakeTaskConstraints_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrbitTaskPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrbitTaskPlatformBase extends _i1.Mock
    implements _i3.OrbitTaskPlatform {
  MockOrbitTaskPlatformBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize(
    void Function(String, Map<String, dynamic>)? taskExecutor, {
    Function? dispatcher,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [taskExecutor],
              {#dispatcher: dispatcher},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleOneTimeTask(_i2.BackgroundTask? task) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleOneTimeTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleRecurringTask(_i2.BackgroundTask? task) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleRecurringTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllTasks, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BackgroundTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackgroundTask extends _i1.Mock implements _i2.BackgroundTask {
  MockBackgroundTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get taskName =>
      (super.noSuchMethod(
            Invocation.getter(#taskName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#taskName),
            ),
          )
          as String);

  @override
  Map<String, dynamic> get inputData =>
      (super.noSuchMethod(
            Invocation.getter(#inputData),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i2.TaskConstraints get constraints =>
      (super.noSuchMethod(
            Invocation.getter(#constraints),
            returnValue: _FakeTaskConstraints_0(
              this,
              Invocation.getter(#constraints),
            ),
          )
          as _i2.TaskConstraints);
}
